OK       = '1'
ADD      = '2'
APPEND   = '3'
GETVALUE = '4'
CREATE   = '5'
STOP     = '6'
HOSTS    = 'localhost' # server
PORTS   = 5000
PORTC1  = 5001
PORTC2  = 5002
HOSTC1  = 'localhost' # ip client 1
HOSTC2  = 'localhost' # ip client 2 (optional)
